### ISSUE TITLE
Support for v1.2, fixes, initial configuration

### ISSUE THREAD

**Issue by mmetc** [sbz/packaging-freebsd#1]
Hi @sbz ,
I am responsible for porting/packaging at CrowdSec. I would like to thank you for your port and contribute some updates.

I forked your repo at https://github.com/crowdsecurity/packaging-freebsd/tree/mm-wip

There you can find

- Bump distribution target: FreeBSD 12.2 -> 13.0

- Bump Crowdsec release: 1.1.1 -> 1.2.0 and firewall-bouncer 0.0.13 -> 0.0.16

- Fixed path issues. Go code in CrowdSec has hardcoded paths for both /etc/crowdsec and /var/lib. We will eventually fix the issue at the source level but in the meantime, sed replacements will do. I extended them to more source files and included the data directory (/var/lib -> /var/db)

- More configuration files provided as ".sample": acquis.yaml, profiles.yaml, simulation.yaml, local_api_credentials and online_api_credentials. The last three are usually not edited by users but need nevertheless to be maintained across updates.

- The port's Makefile builds the CLI binary as crowdsec-cli, but all the Linux ports and the CrowdSec documentation refer to it as cscli, so I renamed the binary after the build.

- The RC script now connects (upon first use) to fetch the hub's inventory, register local/online APIs and download GeoIP data, all while querying cscli to read the right pathnames from the configuration.

- Updated post-install message to tell the user to also edit acquis.yaml and profiles.yaml in addition to config.yaml because we don't detect the running services in FreeBSD (no wizard.sh)

- Deinstall script to stop the service before removing the package.

- minor cleanup: avoid installing unused/legacy files

I have not tested with Cirrus CI, nor have tested the firewall bouncer.

I am undecided about the deinstall script, because if I run "make reinstall" (or, I suppose, in case of upgrade) the service is not run again. This is my first experience in porting to FreeBSD so I'm not aware of the best practices. Shouldn't the service always be re-run if enabled by sysrc?

Except for the last point, I'm ready for a pull request. I expect to keep updating the port for the new releases and plugins. What do you think?

Thanks

**Comment by sbz** [comment]
Hi @mmetc,

Thanks for the great updates, I reviewed all the changes after a **first pass** and everything looks good to me 🤝  , In particular:

* [x] Update FreeBSD image in Cirius-CI to 13.0
* [x] Crowdsec agent and bouncer release bump
* [x] Installing the binary as `cscli` instead of `crowdsec-cli`, it's something I wanted to change too!
* [x] Removing legacy/unused files. _It's a No-op here, but it totally make senses. For updating and pkg-plist maintenances I kept them but I'm glad you chase them_

It looks like that they are few changes in configuration required now, it's great you handle them 💯  

> I have not tested with Cirrus CI, nor have tested the firewall bouncer.
Noted, neither I did.

> I am undecided about the deinstall script, because if I run "make reinstall" (or, I suppose, in case of upgrade) the service is not run again. This is my first experience in porting to FreeBSD so I'm not aware of the best practices. Shouldn't the service always be re-run if enabled by sysrc?

About this, not sure I understand what you mean but imho on FreeBSD, services are never enabled nor started by default, you have to add them to `rc.conf` either manually or via `sysrc` then use the `service` command to start them. 

To make sure we cover all the changes, I'll add my feedbacks/comments inline in the pull request #2

**Comment by mmetc** [comment]
Hi @sbz ,

thanks for the review!

> About this, not sure I understand what you mean but imho on FreeBSD, services are never enabled nor started by default, you have to add them to rc.conf either manually or via sysrc then use the service command to start them.

If I enable (via sysrc) and start the service (via "service crowdsec start") it works until I upgrade the crowdsec package to a new version. When I upgrade, the service is stopped *because I stop it in the deinstall script*. I think I have to stop it, otherwise when I deinstall a package, the daemon keeps running, totally unaware that the package files have been removed. And I have no way to differentiate from deinstall <-> upgrade.

**Comment by sbz** [comment]
It makes sense to stop it in both cases, before an upgrade and before a deinstall. You don't want to leave a running daemon (agent) in memory with no remaining configuration files and binaries on disk.
